version: "3.8"

services:
  atm10:
    image: itzg/minecraft-server:latest
    container_name: ce
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-25565}:25565/tcp"
    environment:
      EULA: "TRUE"
      TZ: "Europe/Paris"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "${CF_SERVER_MOD}"
      INIT_MEMORY: "${INIT_MEMORY:-2G}"
      MAX_MEMORY:  "${MAX_MEMORY:-24G}"
      USE_AIKAR_FLAGS: "true"
      FTB_FORCE_JAVA: "true"
      SKIP_JAVA_CHECK: "true"
      FTB_SKIP_JAVA_CHECK: "true"
      USE_SYSTEM_JAVA: "true"
      FTB_OVERRIDE_START_SCRIPT: "true"
      ENABLE_WHITELIST: "${ENABLE_WHITELIST:-FALSE}"
      DIFFICULTY: "${DIFFICULTY:-normal}"
      MOTD: "${MOTD:-All The Mods 10}"
    volumes:
      - ce_data:/data
volumes:
  ce_data:
